include:
  - "backend/api/**/*.rb"
exclude:
  - "backend/api/.bundle/**/*"
  - "backend/api/test/**/*"
  - "backend/api/vendor/**/*"
require: []
domains: []
reporters:
  - rubocop
  - require_not_found
formatter:
  rubocop:
    cops: safe
    except: []
    only: []
    extra_args: []
require_paths: []
plugins: []
max_files: 5000
